import { createClient } from '@supabase/supabase-js';
import ws from 'ws';

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { global: { fetch: fetch as typeof fetch }, realtime: { transport: ws } }
);

const rows = [
  // ── A1 — V2 basic ────────────────────────────────────────────────────────
  {
    id: 'wo-a1-01',
    words: ['Ik', 'eet', 'elke', 'dag', 'brood'],
    english: 'I eat bread every day.',
    translation_es: 'Como pan todos los días.',
    rule: 'v2',
    explanation: 'V2 rule: the subject (Ik) is in 1st position; the finite verb (eet) is always in 2nd position in a main clause.',
    explanation_es: 'Regla V2: el sujeto (Ik) está en 1ª posición; el verbo (eet) ocupa siempre la 2ª posición en una oración principal.',
    level: 'A1',
  },
  {
    id: 'wo-a1-02',
    words: ['Jij', 'spreekt', 'heel', 'goed', 'Nederlands'],
    english: 'You speak Dutch very well.',
    translation_es: 'Hablas neerlandés muy bien.',
    rule: 'v2',
    explanation: 'V2 rule: subject (Jij) first, finite verb (spreekt) second — then the rest.',
    explanation_es: 'Regla V2: sujeto (Jij) primero, verbo (spreekt) segundo — luego el resto.',
    level: 'A1',
  },
  {
    id: 'wo-a1-03',
    words: ['Hij', 'drinkt', 'elke', 'ochtend', 'koffie'],
    english: 'He drinks coffee every morning.',
    translation_es: 'Él bebe café cada mañana.',
    rule: 'v2',
    explanation: 'V2 rule: subject (Hij) first, verb (drinkt) second.',
    explanation_es: 'Regla V2: sujeto (Hij) primero, verbo (drinkt) segundo.',
    level: 'A1',
  },
  {
    id: 'wo-a1-04',
    words: ['Ze', 'werkt', 'in', 'een', 'ziekenhuis'],
    english: 'She works in a hospital.',
    translation_es: 'Ella trabaja en un hospital.',
    rule: 'v2',
    explanation: 'V2 rule: subject (Ze) first, verb (werkt) second, place last.',
    explanation_es: 'Regla V2: sujeto (Ze) primero, verbo (werkt) segundo, el lugar al final.',
    level: 'A1',
  },
  {
    id: 'wo-a1-05',
    words: ['Wij', 'wonen', 'in', 'een', 'groot', 'huis'],
    english: 'We live in a big house.',
    translation_es: 'Vivimos en una casa grande.',
    rule: 'v2',
    explanation: 'V2 rule: subject (Wij) first, verb (wonen) second.',
    explanation_es: 'Regla V2: sujeto (Wij) primero, verbo (wonen) segundo.',
    level: 'A1',
  },

  // ── A1 — V2 + fronting ───────────────────────────────────────────────────
  {
    id: 'wo-a1-06',
    words: ['Morgen', 'ga', 'ik', 'naar', 'school'],
    english: 'Tomorrow I go to school.',
    translation_es: 'Mañana voy al colegio.',
    rule: 'v2-fronting',
    explanation: 'Fronting: "Morgen" takes 1st position → verb (ga) stays in 2nd → subject (ik) moves to 3rd (inversion).',
    explanation_es: 'Anteposición: "Morgen" ocupa la 1ª posición → el verbo (ga) sigue en 2ª → el sujeto (ik) pasa a 3ª (inversión).',
    level: 'A1',
  },
  {
    id: 'wo-a1-07',
    words: ['Nu', 'drink', 'ik', 'een', 'kopje', 'thee'],
    english: 'Now I drink a cup of tea.',
    translation_es: 'Ahora bebo una taza de té.',
    rule: 'v2-fronting',
    explanation: '"Nu" is fronted → verb (drink) in 2nd position → subject (ik) in 3rd.',
    explanation_es: '"Nu" se antepone → verbo (drink) en 2ª posición → sujeto (ik) en 3ª.',
    level: 'A1',
  },
  {
    id: 'wo-a1-08',
    words: ['Vandaag', 'werkt', 'hij', 'niet'],
    english: 'Today he is not working.',
    translation_es: 'Hoy él no trabaja.',
    rule: 'v2-fronting',
    explanation: '"Vandaag" fronted → verb (werkt) 2nd → subject (hij) 3rd → "niet" at end.',
    explanation_es: '"Vandaag" al principio → verbo (werkt) 2º → sujeto (hij) 3º → "niet" al final.',
    level: 'A1',
  },
  {
    id: 'wo-a1-09',
    words: ['Elke', 'dag', 'leer', 'ik', 'nieuwe', 'woorden'],
    english: 'Every day I learn new words.',
    translation_es: 'Cada día aprendo palabras nuevas.',
    rule: 'v2-fronting',
    explanation: 'Time phrase (Elke dag) fronted → verb (leer) 2nd → subject (ik) 3rd.',
    explanation_es: 'Frase temporal (Elke dag) al principio → verbo (leer) 2º → sujeto (ik) 3º.',
    level: 'A1',
  },
  {
    id: 'wo-a1-10',
    words: ['In', 'de', 'keuken', 'kookt', 'mijn', 'moeder'],
    english: 'In the kitchen, my mother cooks.',
    translation_es: 'En la cocina cocina mi madre.',
    rule: 'v2-fronting',
    explanation: 'Place phrase (In de keuken) fronted → verb (kookt) 2nd → subject (mijn moeder) follows.',
    explanation_es: 'Frase de lugar (In de keuken) al principio → verbo (kookt) 2º → sujeto (mijn moeder) después.',
    level: 'A1',
  },

  // ── A1 — Modal ───────────────────────────────────────────────────────────
  {
    id: 'wo-a1-11',
    words: ['Ik', 'kan', 'goed', 'zwemmen'],
    english: 'I can swim well.',
    translation_es: 'Sé nadar bien.',
    rule: 'modal',
    explanation: 'Modal verb (kan) in 2nd position; the infinitive (zwemmen) goes to the very end.',
    explanation_es: 'El verbo modal (kan) en 2ª posición; el infinitivo (zwemmen) va al final.',
    level: 'A1',
  },
  {
    id: 'wo-a1-12',
    words: ['Hij', 'wil', 'een', 'boek', 'lezen'],
    english: 'He wants to read a book.',
    translation_es: 'Él quiere leer un libro.',
    rule: 'modal',
    explanation: 'Modal verb (wil) in 2nd position; the infinitive (lezen) goes to the end.',
    explanation_es: 'El verbo modal (wil) en 2ª posición; el infinitivo (lezen) va al final.',
    level: 'A1',
  },
  {
    id: 'wo-a1-13',
    words: ['Ze', 'moet', 'vanavond', 'werken'],
    english: 'She has to work this evening.',
    translation_es: 'Ella tiene que trabajar esta tarde.',
    rule: 'modal',
    explanation: 'Modal verb (moet) in 2nd position; the infinitive (werken) at the end.',
    explanation_es: 'El verbo modal (moet) en 2ª posición; el infinitivo (werken) al final.',
    level: 'A1',
  },
  {
    id: 'wo-a1-14',
    words: ['Wij', 'mogen', 'hier', 'niet', 'roken'],
    english: 'We are not allowed to smoke here.',
    translation_es: 'No podemos fumar aquí.',
    rule: 'modal',
    explanation: 'Modal (mogen) in 2nd position; "niet" precedes the infinitive; infinitive (roken) at the end.',
    explanation_es: 'Modal (mogen) en 2ª posición; "niet" precede al infinitivo; infinitivo (roken) al final.',
    level: 'A1',
  },
  {
    id: 'wo-a1-15',
    words: ['Morgen', 'moet', 'ik', 'vroeg', 'opstaan'],
    english: 'Tomorrow I have to get up early.',
    translation_es: 'Mañana tengo que levantarme temprano.',
    rule: 'modal',
    explanation: 'Fronting + modal: "Morgen" → modal (moet) in 2nd → subject (ik) 3rd → infinitive (opstaan) at the end.',
    explanation_es: 'Anteposición + modal: "Morgen" → modal (moet) en 2º → sujeto (ik) 3º → infinitivo (opstaan) al final.',
    level: 'A1',
  },

  // ── A2 — V2 + fronting ───────────────────────────────────────────────────
  {
    id: 'wo-a2-01',
    words: ['In', 'Amsterdam', 'zijn', 'veel', 'mooie', 'grachten'],
    english: 'In Amsterdam there are many beautiful canals.',
    translation_es: 'En Ámsterdam hay muchos canales preciosos.',
    rule: 'v2-fronting',
    explanation: 'Place phrase fronted → finite verb (zijn) in 2nd position → subject (veel mooie grachten) follows.',
    explanation_es: 'Frase de lugar al principio → verbo (zijn) en 2ª posición → sujeto después.',
    level: 'A2',
  },
  {
    id: 'wo-a2-02',
    words: ['Dit', 'jaar', 'gaan', 'we', 'naar', 'Spanje'],
    english: 'This year we are going to Spain.',
    translation_es: 'Este año vamos a España.',
    rule: 'v2-fronting',
    explanation: 'Time phrase (Dit jaar) fronted → verb (gaan) 2nd → subject (we) 3rd.',
    explanation_es: 'Frase temporal (Dit jaar) al principio → verbo (gaan) 2º → sujeto (we) 3º.',
    level: 'A2',
  },
  {
    id: 'wo-a2-03',
    words: ['Soms', 'eet', 'ik', 'geen', 'vlees'],
    english: 'Sometimes I eat no meat.',
    translation_es: 'A veces no como carne.',
    rule: 'v2-fronting',
    explanation: '"Soms" (sometimes) fronted → verb (eet) 2nd → subject (ik) 3rd.',
    explanation_es: '"Soms" (a veces) al principio → verbo (eet) 2º → sujeto (ik) 3º.',
    level: 'A2',
  },
  {
    id: 'wo-a2-04',
    words: ['Elke', 'week', 'gaat', 'hij', 'naar', 'de', 'sportschool'],
    english: 'Every week he goes to the gym.',
    translation_es: 'Cada semana él va al gimnasio.',
    rule: 'v2-fronting',
    explanation: 'Time phrase (Elke week) fronted → verb (gaat) 2nd → subject (hij) 3rd.',
    explanation_es: 'Frase temporal (Elke week) al principio → verbo (gaat) 2º → sujeto (hij) 3º.',
    level: 'A2',
  },

  // ── A2 — Perfect tense ───────────────────────────────────────────────────
  {
    id: 'wo-a2-05',
    words: ['Ik', 'heb', 'de', 'brief', 'geschreven'],
    english: 'I have written the letter.',
    translation_es: 'He escrito la carta.',
    rule: 'perfect',
    explanation: 'Perfect tense: auxiliary (heb) in 2nd position; past participle (geschreven) at the very end.',
    explanation_es: 'Pretérito perfecto: auxiliar (heb) en 2ª posición; participio pasado (geschreven) al final.',
    level: 'A2',
  },
  {
    id: 'wo-a2-06',
    words: ['Gisteren', 'heb', 'ik', 'een', 'film', 'gezien'],
    english: 'Yesterday I watched a film.',
    translation_es: 'Ayer vi una película.',
    rule: 'perfect',
    explanation: 'Fronting + perfect: "Gisteren" → auxiliary (heb) 2nd → subject (ik) 3rd → participle (gezien) at end.',
    explanation_es: 'Anteposición + perfecto: "Gisteren" → auxiliar (heb) 2º → sujeto (ik) 3º → participio (gezien) al final.',
    level: 'A2',
  },
  {
    id: 'wo-a2-07',
    words: ['Ze', 'heeft', 'hem', 'gisteren', 'gebeld'],
    english: 'She called him yesterday.',
    translation_es: 'Ella lo llamó ayer.',
    rule: 'perfect',
    explanation: 'Auxiliary (heeft) in 2nd position; past participle (gebeld) at the end.',
    explanation_es: 'Auxiliar (heeft) en 2ª posición; participio pasado (gebeld) al final.',
    level: 'A2',
  },
  {
    id: 'wo-a2-08',
    words: ['Hij', 'is', 'naar', 'Parijs', 'gevlogen'],
    english: 'He has flown to Paris.',
    translation_es: 'Él ha volado a París.',
    rule: 'perfect',
    explanation: 'Movement verbs use "zijn" as auxiliary. Auxiliary (is) 2nd; participle (gevlogen) at the end.',
    explanation_es: 'Los verbos de movimiento usan "zijn" como auxiliar. Auxiliar (is) 2º; participio (gevlogen) al final.',
    level: 'A2',
  },
  {
    id: 'wo-a2-09',
    words: ['Vorige', 'week', 'hebben', 'we', 'veel', 'gewerkt'],
    english: 'Last week we worked a lot.',
    translation_es: 'La semana pasada trabajamos mucho.',
    rule: 'perfect',
    explanation: '"Vorige week" fronted → auxiliary (hebben) 2nd → subject (we) 3rd → participle (gewerkt) at end.',
    explanation_es: '"Vorige week" al principio → auxiliar (hebben) 2º → sujeto (we) 3º → participio al final.',
    level: 'A2',
  },
  {
    id: 'wo-a2-10',
    words: ['Ik', 'heb', 'gisteren', 'goed', 'geslapen'],
    english: 'I slept well yesterday.',
    translation_es: 'Ayer dormí bien.',
    rule: 'perfect',
    explanation: 'Auxiliary (heb) in 2nd position; adverbs (gisteren, goed) before the participle; participle (geslapen) at the end.',
    explanation_es: 'Auxiliar (heb) en 2ª posición; adverbios antes del participio; participio (geslapen) al final.',
    level: 'A2',
  },

  // ── A2 — Subordinate clause ──────────────────────────────────────────────
  {
    id: 'wo-a2-11',
    words: ['Ik', 'weet', 'dat', 'hij', 'ziek', 'is'],
    english: 'I know that he is sick.',
    translation_es: 'Sé que él está enfermo.',
    rule: 'subordinate',
    explanation: 'After "dat" (that), the finite verb moves to the end of the subordinate clause.',
    explanation_es: 'Después de "dat" (que), el verbo va al final de la oración subordinada.',
    level: 'A2',
  },
  {
    id: 'wo-a2-12',
    words: ['Ze', 'blijft', 'thuis', 'omdat', 'het', 'regent'],
    english: 'She stays home because it is raining.',
    translation_es: 'Ella se queda en casa porque llueve.',
    rule: 'subordinate',
    explanation: 'After "omdat" (because), the verb (regent) goes to the end of the clause.',
    explanation_es: 'Después de "omdat" (porque), el verbo (regent) va al final de la oración.',
    level: 'A2',
  },
  {
    id: 'wo-a2-13',
    words: ['Ik', 'weet', 'niet', 'of', 'zij', 'komt'],
    english: 'I do not know whether she is coming.',
    translation_es: 'No sé si ella viene.',
    rule: 'subordinate',
    explanation: 'After "of" (whether/if), the verb (komt) goes to the end of the clause.',
    explanation_es: 'Después de "of" (si), el verbo (komt) va al final de la oración.',
    level: 'A2',
  },
  {
    id: 'wo-a2-14',
    words: ['Hij', 'zegt', 'dat', 'hij', 'morgen', 'komt'],
    english: 'He says that he is coming tomorrow.',
    translation_es: 'Él dice que vendrá mañana.',
    rule: 'subordinate',
    explanation: 'After "dat", the verb (komt) goes to the end; adverbs like "morgen" come directly before the verb.',
    explanation_es: 'Después de "dat", el verbo (komt) va al final; los adverbios como "morgen" van justo antes del verbo.',
    level: 'A2',
  },
  {
    id: 'wo-a2-15',
    words: ['Ik', 'ga', 'naar', 'huis', 'als', 'het', 'regent'],
    english: 'I go home when it rains.',
    translation_es: 'Me voy a casa cuando llueve.',
    rule: 'subordinate',
    explanation: 'After "als" (when/if), the verb (regent) goes to the end of the clause.',
    explanation_es: 'Después de "als" (cuando/si), el verbo (regent) va al final de la oración.',
    level: 'A2',
  },
  {
    id: 'wo-a2-16',
    words: ['Zij', 'lacht', 'als', 'ze', 'hem', 'ziet'],
    english: 'She laughs when she sees him.',
    translation_es: 'Ella ríe cuando lo ve.',
    rule: 'subordinate',
    explanation: 'After "als" (when), the verb (ziet) goes to the end of the clause.',
    explanation_es: 'Después de "als" (cuando), el verbo (ziet) va al final de la oración.',
    level: 'A2',
  },
  {
    id: 'wo-a2-17',
    words: ['Ik', 'begrijp', 'niet', 'waarom', 'hij', 'boos', 'is'],
    english: 'I do not understand why he is angry.',
    translation_es: 'No entiendo por qué él está enfadado.',
    rule: 'subordinate',
    explanation: 'After "waarom" (why), the verb (is) goes to the end of the clause.',
    explanation_es: 'Después de "waarom" (por qué), el verbo (is) va al final de la oración.',
    level: 'A2',
  },
  {
    id: 'wo-a2-18',
    words: ['Ze', 'weet', 'hoeveel', 'het', 'kost'],
    english: 'She knows how much it costs.',
    translation_es: 'Ella sabe cuánto cuesta.',
    rule: 'subordinate',
    explanation: 'After "hoeveel" (how much), the verb (kost) goes to the end of the clause.',
    explanation_es: 'Después de "hoeveel" (cuánto), el verbo (kost) va al final de la oración.',
    level: 'A2',
  },
  {
    id: 'wo-a2-19',
    words: ['We', 'eten', 'pas', 'als', 'iedereen', 'er', 'is'],
    english: 'We only eat when everyone is there.',
    translation_es: 'Solo comemos cuando están todos.',
    rule: 'subordinate',
    explanation: 'After "als" (when), the verb (is) goes to the end.',
    explanation_es: 'Después de "als" (cuando), el verbo (is) va al final.',
    level: 'A2',
  },
  {
    id: 'wo-a2-20',
    words: ['Ik', 'leer', 'Nederlands', 'omdat', 'ik', 'in', 'Nederland', 'woon'],
    english: 'I learn Dutch because I live in the Netherlands.',
    translation_es: 'Aprendo neerlandés porque vivo en los Países Bajos.',
    rule: 'subordinate',
    explanation: 'After "omdat" (because), the verb (woon) goes to the very end of the subordinate clause.',
    explanation_es: 'Después de "omdat" (porque), el verbo (woon) va al final de la oración subordinada.',
    level: 'A2',
  },
  {
    id: 'wo-a2-21',
    words: ['Ze', 'wacht', 'totdat', 'de', 'trein', 'aankomt'],
    english: 'She waits until the train arrives.',
    translation_es: 'Ella espera hasta que llegue el tren.',
    rule: 'subordinate',
    explanation: 'After "totdat" (until), the verb (aankomt) goes to the end.',
    explanation_es: 'Después de "totdat" (hasta que), el verbo (aankomt) va al final.',
    level: 'A2',
  },
  {
    id: 'wo-a2-22',
    words: ['Ik', 'snap', 'niet', 'hoe', 'hij', 'dat', 'doet'],
    english: 'I do not understand how he does that.',
    translation_es: 'No entiendo cómo hace eso.',
    rule: 'subordinate',
    explanation: 'After "hoe" (how), the verb (doet) goes to the end of the clause.',
    explanation_es: 'Después de "hoe" (cómo), el verbo (doet) va al final de la oración.',
    level: 'A2',
  },

  // ── B1 — Subordinate + perfect ───────────────────────────────────────────
  {
    id: 'wo-b1-01',
    words: ['Ik', 'weet', 'dat', 'hij', 'al', 'vertrokken', 'is'],
    english: 'I know that he has already left.',
    translation_es: 'Sé que él ya se ha ido.',
    rule: 'subordinate',
    explanation: 'Subordinate + perfect: adverb (al) → participle (vertrokken) → auxiliary (is) — all three at the end, in that order.',
    explanation_es: 'Subordinada + perfecto: adverbio (al) → participio (vertrokken) → auxiliar (is) — los tres al final, en ese orden.',
    level: 'B1',
  },
  {
    id: 'wo-b1-02',
    words: ['Ze', 'zegt', 'dat', 'ze', 'het', 'boek', 'gelezen', 'heeft'],
    english: 'She says that she has read the book.',
    translation_es: 'Ella dice que ha leído el libro.',
    rule: 'subordinate',
    explanation: 'Subordinate + perfect: object (het boek) → participle (gelezen) → auxiliary (heeft) at the very end.',
    explanation_es: 'Subordinada + perfecto: objeto (het boek) → participio (gelezen) → auxiliar (heeft) al final.',
    level: 'B1',
  },
  {
    id: 'wo-b1-03',
    words: ['Ik', 'hoop', 'dat', 'je', 'goed', 'geslapen', 'hebt'],
    english: 'I hope that you slept well.',
    translation_es: 'Espero que hayas dormido bien.',
    rule: 'subordinate',
    explanation: 'Subordinate + perfect: adverb (goed) → participle (geslapen) → auxiliary (hebt) at the end.',
    explanation_es: 'Subordinada + perfecto: adverbio (goed) → participio (geslapen) → auxiliar (hebt) al final.',
    level: 'B1',
  },
  {
    id: 'wo-b1-04',
    words: ['Hij', 'vertelt', 'dat', 'ze', 'gisteren', 'aangekomen', 'zijn'],
    english: 'He says that they arrived yesterday.',
    translation_es: 'Él dice que llegaron ayer.',
    rule: 'subordinate',
    explanation: 'Subordinate + perfect with "zijn": adverb (gisteren) → participle (aangekomen) → auxiliary (zijn) at the end.',
    explanation_es: 'Subordinada + perfecto con "zijn": adverbio (gisteren) → participio (aangekomen) → auxiliar (zijn) al final.',
    level: 'B1',
  },

  // ── B1 — Subordinate + modal ──────────────────────────────────────────────
  {
    id: 'wo-b1-05',
    words: ['Ze', 'zegt', 'dat', 'hij', 'niet', 'mag', 'komen'],
    english: 'She says that he is not allowed to come.',
    translation_es: 'Ella dice que él no puede venir.',
    rule: 'subordinate',
    explanation: 'Subordinate + modal: "niet" → modal (mag) → infinitive (komen) at the end.',
    explanation_es: 'Subordinada + modal: "niet" → modal (mag) → infinitivo (komen) al final.',
    level: 'B1',
  },
  {
    id: 'wo-b1-06',
    words: ['Ik', 'weet', 'dat', 'ze', 'dit', 'moet', 'doen'],
    english: 'I know that she has to do this.',
    translation_es: 'Sé que ella tiene que hacer esto.',
    rule: 'subordinate',
    explanation: 'Subordinate + modal: object (dit) → modal (moet) → infinitive (doen) at the end.',
    explanation_es: 'Subordinada + modal: objeto (dit) → modal (moet) → infinitivo (doen) al final.',
    level: 'B1',
  },
  {
    id: 'wo-b1-07',
    words: ['Hij', 'denkt', 'dat', 'hij', 'morgen', 'kan', 'vertrekken'],
    english: 'He thinks that he can leave tomorrow.',
    translation_es: 'Él cree que puede irse mañana.',
    rule: 'subordinate',
    explanation: 'Subordinate + modal: adverb (morgen) → modal (kan) → infinitive (vertrekken) at the end.',
    explanation_es: 'Subordinada + modal: adverbio (morgen) → modal (kan) → infinitivo (vertrekken) al final.',
    level: 'B1',
  },
  {
    id: 'wo-b1-08',
    words: ['Ze', 'hoopt', 'dat', 'we', 'vroeg', 'kunnen', 'beginnen'],
    english: 'She hopes that we can start early.',
    translation_es: 'Ella espera que podamos empezar pronto.',
    rule: 'subordinate',
    explanation: 'Subordinate + modal: adverb (vroeg) → modal (kunnen) → infinitive (beginnen) at the end.',
    explanation_es: 'Subordinada + modal: adverbio (vroeg) → modal (kunnen) → infinitivo (beginnen) al final.',
    level: 'B1',
  },

  // ── B1 — Complex V2 + fronting ────────────────────────────────────────────
  {
    id: 'wo-b1-09',
    words: ['Gelukkig', 'is', 'alles', 'goed', 'gegaan'],
    english: 'Fortunately, everything went well.',
    translation_es: 'Por suerte, todo salió bien.',
    rule: 'v2-fronting',
    explanation: '"Gelukkig" (fortunately) fronted → auxiliary (is) in 2nd → subject (alles) 3rd → participle (gegaan) at end.',
    explanation_es: '"Gelukkig" al principio → auxiliar (is) 2º → sujeto (alles) 3º → participio (gegaan) al final.',
    level: 'B1',
  },
  {
    id: 'wo-b1-10',
    words: ['Pas', 'gisteren', 'heb', 'ik', 'dat', 'gehoord'],
    english: 'Only yesterday did I hear that.',
    translation_es: 'Solo ayer oí eso.',
    rule: 'v2-fronting',
    explanation: '"Pas gisteren" fronted → auxiliary (heb) 2nd → subject (ik) 3rd → participle (gehoord) at end.',
    explanation_es: '"Pas gisteren" al principio → auxiliar (heb) 2º → sujeto (ik) 3º → participio (gehoord) al final.',
    level: 'B1',
  },
  {
    id: 'wo-b1-11',
    words: ['Toch', 'gaat', 'hij', 'niet', 'mee'],
    english: 'Still, he is not coming along.',
    translation_es: 'Aun así, él no viene.',
    rule: 'v2-fronting',
    explanation: '"Toch" (still/yet) fronted → verb (gaat) 2nd → subject (hij) 3rd → rest follows.',
    explanation_es: '"Toch" (aun así) al principio → verbo (gaat) 2º → sujeto (hij) 3º → el resto sigue.',
    level: 'B1',
  },
  {
    id: 'wo-b1-12',
    words: ['Normaal', 'gesproken', 'eet', 'ik', 'om', 'zes', 'uur'],
    english: 'Normally I eat at six o\'clock.',
    translation_es: 'Normalmente como a las seis.',
    rule: 'v2-fronting',
    explanation: '"Normaal gesproken" (normally) is a multi-word adverb fronted as one unit → verb (eet) 2nd → subject (ik) 3rd.',
    explanation_es: '"Normaal gesproken" es un adverbio compuesto que se antepone como una unidad → verbo (eet) 2º → sujeto (ik) 3º.',
    level: 'B1',
  },

  // ── B1 — "Toen" clause (subordinate-as-1st-element → V2 in main clause) ──
  {
    id: 'wo-b1-13',
    words: ['Toen', 'ik', 'klein', 'was', 'woonde', 'ik', 'in', 'Utrecht'],
    english: 'When I was young I lived in Utrecht.',
    translation_es: 'Cuando era pequeño vivía en Utrecht.',
    rule: 'subordinate',
    explanation: '"Toen ik klein was" is a subordinate clause (verb "was" at end). It acts as element 1 → main clause verb (woonde) must be in 2nd position → subject (ik) follows.',
    explanation_es: '"Toen ik klein was" es una oración subordinada (verbo "was" al final). Funciona como elemento 1 → el verbo principal (woonde) debe ir en 2ª posición → el sujeto (ik) sigue.',
    level: 'B1',
  },
  {
    id: 'wo-b1-14',
    words: ['Ze', 'vraagt', 'wanneer', 'de', 'trein', 'vertrekt'],
    english: 'She asks when the train departs.',
    translation_es: 'Ella pregunta cuándo sale el tren.',
    rule: 'subordinate',
    explanation: 'After "wanneer" (when, as a conjunction), the verb (vertrekt) goes to the end of the embedded clause.',
    explanation_es: 'Después de "wanneer" (cuándo, como conjunción), el verbo (vertrekt) va al final de la oración subordinada.',
    level: 'B1',
  },
];

async function main() {
  console.log(`Inserting ${rows.length} word-order sentences…`);
  const { error } = await supabase
    .from('word_order_sentences')
    .upsert(rows, { onConflict: 'id' });
  if (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
  console.log('Done.');
}

main();
