import { createClient } from '@supabase/supabase-js';
import ws from 'ws';

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { global: { fetch: fetch as typeof fetch }, realtime: { transport: ws } }
);

// Dutch idioms — "complete the expression". The blank is the key word that
// defines the idiom; `english` is the meaning (shown as the gloss). Distractors
// are plausible near-words (body parts, animals, near-synonyms).
const rows = [
  { id: 'expr-gaten', dutch: 'Hou de kinderen goed in de ___.', english: 'to keep an eye on', translation_es: 'vigilar / estar atento a', answer: 'gaten', options: ['gaten', 'ogen', 'wacht', 'zeil'], explanation: '“in de gaten houden” — literally “keep in the holes” — to keep an eye on / watch closely.', explanation_es: '“in de gaten houden” — literalmente “tener en los agujeros” — vigilar, estar atento.', level: 'A2' },
  { id: 'expr-knie', dutch: 'Ik krijg het Nederlands eindelijk onder de ___.', english: 'to master / get the hang of', translation_es: 'dominar / cogerle el truco', answer: 'knie', options: ['knie', 'voet', 'hand', 'arm'], explanation: '“onder de knie krijgen” — literally “get under the knee” — to master a skill.', explanation_es: '“onder de knie krijgen” — literalmente “poner bajo la rodilla” — dominar una habilidad.', level: 'A2' },
  { id: 'expr-kop', dutch: "Daar sla je de spijker op z'n ___.", english: 'to hit the nail on the head', translation_es: 'dar en el clavo', answer: 'kop', options: ['kop', 'hoofd', 'punt', 'neus'], explanation: '“de spijker op z’n kop slaan” — literally “hit the nail on its head” — to be exactly right.', explanation_es: '“de spijker op z’n kop slaan” — literalmente “dar al clavo en la cabeza” — acertar de pleno.', level: 'B1' },
  { id: 'expr-knoop', dutch: 'Na lang twijfelen hakte hij de ___ door.', english: 'to make the decision', translation_es: 'tomar la decisión', answer: 'knoop', options: ['knoop', 'draad', 'band', 'touw'], explanation: '“de knoop doorhakken” — literally “cut the knot” — to finally make a decision.', explanation_es: '“de knoop doorhakken” — literalmente “cortar el nudo” — tomar por fin una decisión.', level: 'B1' },
  { id: 'expr-mouwen', dutch: 'Kom, steek de handen uit de ___!', english: 'to roll up your sleeves, get to work', translation_es: 'ponerse manos a la obra', answer: 'mouwen', options: ['mouwen', 'zakken', 'handschoenen', 'jas'], explanation: '“de handen uit de mouwen steken” — literally “stick your hands out of the sleeves” — to get to work.', explanation_es: '“de handen uit de mouwen steken” — literalmente “sacar las manos de las mangas” — ponerse a trabajar.', level: 'B1' },
  { id: 'expr-deur', dutch: 'Sorry dat ik met de ___ in huis val, maar…', english: 'to get straight to the point', translation_es: 'ir directo al grano', answer: 'deur', options: ['deur', 'raam', 'poort', 'sleutel'], explanation: '“met de deur in huis vallen” — literally “fall into the house with the door” — to come straight to the point.', explanation_es: '“met de deur in huis vallen” — literalmente “entrar en casa con la puerta” — ir directo al grano.', level: 'B1' },
  { id: 'expr-i', dutch: 'We moeten nog de puntjes op de ___ zetten.', english: 'to add the finishing touches', translation_es: 'dar los últimos retoques', answer: 'i', options: ['i', 'a', 'e', 'o'], explanation: '“de puntjes op de i zetten” — literally “put the dots on the i” — to add the finishing touches / be precise.', explanation_es: '“de puntjes op de i zetten” — literalmente “poner los puntos sobre la i” — dar los últimos retoques.', level: 'B1' },
  { id: 'expr-boom', dutch: 'Hij wacht af en kijkt de kat uit de ___.', english: 'to wait and see before acting', translation_es: 'esperar a ver qué pasa', answer: 'boom', options: ['boom', 'zak', 'mand', 'struik'], explanation: '“de kat uit de boom kijken” — literally “watch the cat out of the tree” — to wait and see before committing.', explanation_es: '“de kat uit de boom kijken” — literalmente “mirar al gato salir del árbol” — esperar antes de actuar.', level: 'B1' },
  { id: 'expr-plank', dutch: 'Met die opmerking sla je de ___ mis.', english: 'to be completely wrong / miss the point', translation_es: 'errar el tiro', answer: 'plank', options: ['plank', 'spijker', 'bal', 'plaat'], explanation: '“de plank misslaan” — literally “miss the plank” — to be completely wrong.', explanation_es: '“de plank misslaan” — literalmente “fallar la tabla” — equivocarse por completo.', level: 'B1' },
  { id: 'expr-kaas', dutch: 'Van boekhouden heb ik geen ___ gegeten.', english: 'to know nothing about something', translation_es: 'no tener ni idea de algo', answer: 'kaas', options: ['kaas', 'brood', 'verstand', 'benul'], explanation: '“ergens geen kaas van gegeten hebben” — literally “to have eaten no cheese of it” — to know nothing about it.', explanation_es: '“ergens geen kaas van gegeten hebben” — literalmente “no haber comido queso de ello” — no tener ni idea.', level: 'B1' },
  { id: 'expr-riem', dutch: 'Haar bericht stak me een hart onder de ___.', english: 'to encourage / reassure someone', translation_es: 'dar ánimos a alguien', answer: 'riem', options: ['riem', 'broek', 'jas', 'gordel'], explanation: '“een hart onder de riem steken” — literally “stick a heart under the belt” — to encourage someone.', explanation_es: '“een hart onder de riem steken” — literalmente “meter un corazón bajo el cinturón” — dar ánimos.', level: 'B1' },
  { id: 'expr-boter', dutch: "Hij klaagt, maar heeft zelf ___ op z'n hoofd.", english: 'to be guilty yourself (people in glass houses)', translation_es: 'tener rabo de paja', answer: 'boter', options: ['boter', 'kaas', 'melk', 'olie'], explanation: '“boter op je hoofd hebben” — literally “to have butter on your head” — to be guilty of the very thing you criticise.', explanation_es: '“boter op je hoofd hebben” — literalmente “tener mantequilla en la cabeza” — tener rabo de paja.', level: 'B1' },
  { id: 'expr-dans', dutch: 'Door puur geluk ontsprong ze de ___.', english: 'to have a narrow escape', translation_es: 'librarse por los pelos', answer: 'dans', options: ['dans', 'dood', 'straf', 'bui'], explanation: '“de dans ontspringen” — literally “to jump out of the dance” — to narrowly escape trouble.', explanation_es: '“de dans ontspringen” — literalmente “escapar del baile” — librarse por los pelos.', level: 'B1' },
  { id: 'expr-zak', dutch: 'Die auto was meteen kapot — ik kocht de kat in de ___.', english: 'to be cheated / buy something worthless', translation_es: 'comprar gato por liebre', answer: 'zak', options: ['zak', 'doos', 'mand', 'tas'], explanation: '“de kat in de zak kopen” — literally “buy the cat in the bag” — to be cheated into buying something worthless.', explanation_es: '“de kat in de zak kopen” — literalmente “comprar el gato en el saco” — comprar gato por liebre.', level: 'B1' },
  { id: 'expr-olifant', dutch: 'Stel je niet aan, je maakt van een mug een ___.', english: 'to make a mountain out of a molehill', translation_es: 'hacer una montaña de un grano de arena', answer: 'olifant', options: ['olifant', 'berg', 'reus', 'paard'], explanation: '“van een mug een olifant maken” — literally “make an elephant out of a mosquito” — to exaggerate.', explanation_es: '“van een mug een olifant maken” — literalmente “hacer un elefante de un mosquito” — exagerar.', level: 'B1' },
  { id: 'expr-horens', dutch: 'Vat de koe bij de ___ en begin gewoon.', english: 'to take the bull by the horns', translation_es: 'coger el toro por los cuernos', answer: 'horens', options: ['horens', 'staart', 'poten', 'kop'], explanation: '“de koe bij de horens vatten” — literally “grab the cow by the horns” — to tackle a problem head-on.', explanation_es: '“de koe bij de horens vatten” — literalmente “coger la vaca por los cuernos” — afrontar el problema.', level: 'B1' },
  { id: 'expr-appel', dutch: 'Het is saai werk, maar je moet door de zure ___ heen bijten.', english: 'to bite the bullet', translation_es: 'hacer de tripas corazón', answer: 'appel', options: ['appel', 'peer', 'citroen', 'druif'], explanation: '“door de zure appel heen bijten” — literally “bite through the sour apple” — to endure something unpleasant.', explanation_es: '“door de zure appel heen bijten” — literalmente “morder la manzana agria” — hacer de tripas corazón.', level: 'B1' },
  { id: 'expr-handdoek', dutch: 'Na drie pogingen gooide hij de ___ in de ring.', english: 'to throw in the towel / give up', translation_es: 'tirar la toalla', answer: 'handdoek', options: ['handdoek', 'doek', 'spons', 'deken'], explanation: '“de handdoek in de ring gooien” — literally “throw the towel in the ring” — to give up.', explanation_es: '“de handdoek in de ring gooien” — literalmente “tirar la toalla al ring” — rendirse.', level: 'B1' },
  { id: 'expr-pijpenstelen', dutch: 'Neem een paraplu, het regent ___.', english: 'to rain cats and dogs', translation_es: 'llover a cántaros', answer: 'pijpenstelen', options: ['pijpenstelen', 'katten', 'emmers', 'bakstenen'], explanation: '“het regent pijpenstelen” — literally “it’s raining pipe stems” — it’s pouring down.', explanation_es: '“het regent pijpenstelen” — literalmente “llueven cañas de pipa” — llueve a cántaros.', level: 'B1' },
  { id: 'expr-bloemetjes', dutch: 'Ze was geslaagd en zette de ___ buiten.', english: 'to paint the town red / celebrate', translation_es: 'irse de juerga', answer: 'bloemetjes', options: ['bloemetjes', 'planten', 'tafels', 'stoelen'], explanation: '“de bloemetjes buitenzetten” — literally “put the little flowers outside” — to go out and celebrate.', explanation_es: '“de bloemetjes buitenzetten” — literalmente “sacar las florecitas fuera” — irse de fiesta.', level: 'B1' },
  { id: 'expr-dak', dutch: "Het publiek ging helemaal uit z'n ___.", english: 'to go wild / have a blast', translation_es: 'volverse loco (de emoción)', answer: 'dak', options: ['dak', 'huis', 'muur', 'raam'], explanation: '“uit je dak gaan” — literally “to go out of your roof” — to go wild with excitement.', explanation_es: '“uit je dak gaan” — literalmente “salirse del tejado” — desmadrarse de emoción.', level: 'B1' },
  { id: 'expr-draad', dutch: 'Sorry, waar was ik? Ik ben de ___ kwijt.', english: 'to lose the train of thought', translation_es: 'perder el hilo', answer: 'draad', options: ['draad', 'weg', 'sleutel', 'tijd'], explanation: '“de draad kwijt zijn” — literally “to have lost the thread” — to lose your train of thought.', explanation_es: '“de draad kwijt zijn” — literalmente “haber perdido el hilo” — perder el hilo.', level: 'A2' },
  { id: 'expr-appeltje', dutch: 'Ik heb nog een ___ met jou te schillen.', english: 'to have a bone to pick', translation_es: 'tener cuentas pendientes', answer: 'appeltje', options: ['appeltje', 'eitje', 'peertje', 'nootje'], explanation: '“een appeltje met iemand te schillen hebben” — literally “to have an apple to peel with someone” — to have a bone to pick.', explanation_es: '“een appeltje te schillen hebben” — literalmente “tener una manzanita que pelar” — tener cuentas pendientes.', level: 'B1' },
  { id: 'expr-vingers', dutch: 'De leraar zag het te laat komen door de ___.', english: 'to turn a blind eye', translation_es: 'hacer la vista gorda', answer: 'vingers', options: ['vingers', 'ogen', 'oren', 'handen'], explanation: '“iets door de vingers zien” — literally “to see it through the fingers” — to turn a blind eye.', explanation_es: '“iets door de vingers zien” — literalmente “verlo a través de los dedos” — hacer la vista gorda.', level: 'B1' },
];

async function main() {
  console.log(`Inserting ${rows.length} expression exercises…`);
  const { error } = await supabase.from('expression_exercises').upsert(rows, { onConflict: 'id' });
  if (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
  console.log('Done.');
}

main();
