import { createClient } from '@supabase/supabase-js';
import ws from 'ws';

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { global: { fetch: fetch as typeof fetch }, realtime: { transport: ws } }
);

// Four adjective sub-exercises in one table, tagged by `kind`.
const rows = [
  // ── INFLECTION: the -e rule (options = [inflected, bare]) ──────────────────
  { id: 'adj-inf-de-man', kind: 'inflection', prompt: 'de ___ man', gloss_en: 'big', gloss_es: 'grande', answer: 'grote', answer_es: null, options: ['grote', 'groot'], options_es: null, explanation: 'After “de”, the adjective always takes -e: de grote man.', explanation_es: 'Tras “de”, el adjetivo siempre lleva -e: de grote man.', level: 'A2' },
  { id: 'adj-inf-een-vrouw', kind: 'inflection', prompt: 'een ___ vrouw', gloss_en: 'young', gloss_es: 'joven', answer: 'jonge', answer_es: null, options: ['jonge', 'jong'], options_es: null, explanation: '“vrouw” is a de-word, so it takes -e even after “een”: een jonge vrouw.', explanation_es: '“vrouw” es palabra de-, así que lleva -e incluso tras “een”: een jonge vrouw.', level: 'A2' },
  { id: 'adj-inf-een-huis', kind: 'inflection', prompt: 'een ___ huis', gloss_en: 'big', gloss_es: 'grande', answer: 'groot', answer_es: null, options: ['groot', 'grote'], options_es: null, explanation: 'het-word + singular + indefinite (een) → NO -e: een groot huis.', explanation_es: 'palabra het- + singular + indefinido (een) → SIN -e: een groot huis.', level: 'A2' },
  { id: 'adj-inf-het-huis', kind: 'inflection', prompt: 'het ___ huis', gloss_en: 'big', gloss_es: 'grande', answer: 'grote', answer_es: null, options: ['grote', 'groot'], options_es: null, explanation: 'het-word but definite (“het”) → -e: het grote huis.', explanation_es: 'palabra het- pero definida (“het”) → -e: het grote huis.', level: 'A2' },
  { id: 'adj-inf-huizen', kind: 'inflection', prompt: '___ huizen', gloss_en: 'big', gloss_es: 'grandes', answer: 'grote', answer_es: null, options: ['grote', 'groot'], options_es: null, explanation: 'Plural nouns always take -e: grote huizen.', explanation_es: 'Los sustantivos en plural siempre llevan -e: grote huizen.', level: 'A2' },
  { id: 'adj-inf-pred', kind: 'inflection', prompt: 'Het huis is ___.', gloss_en: 'big', gloss_es: 'grande', answer: 'groot', answer_es: null, options: ['groot', 'grote'], options_es: null, explanation: 'Predicative (after zijn/worden) → never -e: het huis is groot.', explanation_es: 'Predicativo (tras zijn/worden) → nunca -e: het huis is groot.', level: 'A2' },
  { id: 'adj-inf-de-auto', kind: 'inflection', prompt: 'de ___ auto', gloss_en: 'red', gloss_es: 'rojo', answer: 'rode', answer_es: null, options: ['rode', 'rood'], options_es: null, explanation: 'de-word → -e; note the spelling: rood → rode (one o in an open syllable).', explanation_es: 'palabra de- → -e; ojo con la ortografía: rood → rode (una o en sílaba abierta).', level: 'B1' },
  { id: 'adj-inf-een-kind', kind: 'inflection', prompt: 'een ___ kind', gloss_en: 'sweet', gloss_es: 'dulce', answer: 'lief', answer_es: null, options: ['lief', 'lieve'], options_es: null, explanation: '“kind” is a het-word: singular + indefinite → no -e: een lief kind.', explanation_es: '“kind” es palabra het-: singular + indefinido → sin -e: een lief kind.', level: 'A2' },
  { id: 'adj-inf-het-kind', kind: 'inflection', prompt: 'het ___ kind', gloss_en: 'sweet', gloss_es: 'dulce', answer: 'lieve', answer_es: null, options: ['lieve', 'lief'], options_es: null, explanation: 'Definite (“het”) → -e: het lieve kind.', explanation_es: 'Definido (“het”) → -e: het lieve kind.', level: 'A2' },
  { id: 'adj-inf-een-tafel', kind: 'inflection', prompt: 'een ___ tafel', gloss_en: 'big', gloss_es: 'grande', answer: 'grote', answer_es: null, options: ['grote', 'groot'], options_es: null, explanation: '“tafel” is a de-word → -e even after “een”: een grote tafel.', explanation_es: '“tafel” es palabra de- → -e incluso tras “een”: een grote tafel.', level: 'A2' },
  { id: 'adj-inf-geen-probleem', kind: 'inflection', prompt: 'Dat is geen ___ probleem.', gloss_en: 'big', gloss_es: 'grande', answer: 'groot', answer_es: null, options: ['groot', 'grote'], options_es: null, explanation: '“geen” + het-word (probleem) singular → no -e: geen groot probleem.', explanation_es: '“geen” + palabra het- (probleem) singular → sin -e: geen groot probleem.', level: 'B1' },
  { id: 'adj-inf-mijn-huis', kind: 'inflection', prompt: 'mijn ___ huis', gloss_en: 'new', gloss_es: 'nuevo', answer: 'nieuwe', answer_es: null, options: ['nieuwe', 'nieuw'], options_es: null, explanation: 'A possessive (mijn) makes it definite → -e even for a het-word: mijn nieuwe huis.', explanation_es: 'Un posesivo (mijn) lo hace definido → -e incluso en palabra het-: mijn nieuwe huis.', level: 'B1' },
  { id: 'adj-inf-een-horloge', kind: 'inflection', prompt: 'een ___ horloge', gloss_en: 'expensive', gloss_es: 'caro', answer: 'duur', answer_es: null, options: ['duur', 'dure'], options_es: null, explanation: '“horloge” is a het-word: singular + indefinite → no -e: een duur horloge.', explanation_es: '“horloge” es palabra het-: singular + indefinido → sin -e: een duur horloge.', level: 'B1' },
  { id: 'adj-inf-de-stad', kind: 'inflection', prompt: 'de ___ stad', gloss_en: 'old', gloss_es: 'antigua', answer: 'oude', answer_es: null, options: ['oude', 'oud'], options_es: null, explanation: 'de-word → -e: de oude stad.', explanation_es: 'palabra de- → -e: de oude stad.', level: 'A2' },

  // ── VOCAB: Dutch adjective → meaning (options localised) ───────────────────
  { id: 'adj-voc-snel', kind: 'vocab', prompt: 'snel', gloss_en: null, gloss_es: null, answer: 'fast', answer_es: 'rápido', options: ['fast', 'slow', 'heavy', 'easy'], options_es: ['rápido', 'lento', 'pesado', 'fácil'], explanation: 'snel = fast.', explanation_es: 'snel = rápido.', level: 'A1' },
  { id: 'adj-voc-groot', kind: 'vocab', prompt: 'groot', gloss_en: null, gloss_es: null, answer: 'big', answer_es: 'grande', options: ['big', 'small', 'tall', 'wide'], options_es: ['grande', 'pequeño', 'alto', 'ancho'], explanation: 'groot = big.', explanation_es: 'groot = grande.', level: 'A1' },
  { id: 'adj-voc-klein', kind: 'vocab', prompt: 'klein', gloss_en: null, gloss_es: null, answer: 'small', answer_es: 'pequeño', options: ['small', 'big', 'short', 'thin'], options_es: ['pequeño', 'grande', 'corto', 'delgado'], explanation: 'klein = small.', explanation_es: 'klein = pequeño.', level: 'A1' },
  { id: 'adj-voc-duur', kind: 'vocab', prompt: 'duur', gloss_en: null, gloss_es: null, answer: 'expensive', answer_es: 'caro', options: ['expensive', 'cheap', 'rich', 'heavy'], options_es: ['caro', 'barato', 'rico', 'pesado'], explanation: 'duur = expensive.', explanation_es: 'duur = caro.', level: 'A2' },
  { id: 'adj-voc-goedkoop', kind: 'vocab', prompt: 'goedkoop', gloss_en: null, gloss_es: null, answer: 'cheap', answer_es: 'barato', options: ['cheap', 'expensive', 'easy', 'poor'], options_es: ['barato', 'caro', 'fácil', 'pobre'], explanation: 'goedkoop = cheap.', explanation_es: 'goedkoop = barato.', level: 'A2' },
  { id: 'adj-voc-moeilijk', kind: 'vocab', prompt: 'moeilijk', gloss_en: null, gloss_es: null, answer: 'difficult', answer_es: 'difícil', options: ['difficult', 'easy', 'heavy', 'slow'], options_es: ['difícil', 'fácil', 'pesado', 'lento'], explanation: 'moeilijk = difficult.', explanation_es: 'moeilijk = difícil.', level: 'A2' },
  { id: 'adj-voc-makkelijk', kind: 'vocab', prompt: 'makkelijk', gloss_en: null, gloss_es: null, answer: 'easy', answer_es: 'fácil', options: ['easy', 'difficult', 'fast', 'light'], options_es: ['fácil', 'difícil', 'rápido', 'ligero'], explanation: 'makkelijk = easy.', explanation_es: 'makkelijk = fácil.', level: 'A2' },
  { id: 'adj-voc-mooi', kind: 'vocab', prompt: 'mooi', gloss_en: null, gloss_es: null, answer: 'beautiful', answer_es: 'bonito', options: ['beautiful', 'ugly', 'expensive', 'clean'], options_es: ['bonito', 'feo', 'caro', 'limpio'], explanation: 'mooi = beautiful / nice.', explanation_es: 'mooi = bonito.', level: 'A1' },
  { id: 'adj-voc-lelijk', kind: 'vocab', prompt: 'lelijk', gloss_en: null, gloss_es: null, answer: 'ugly', answer_es: 'feo', options: ['ugly', 'beautiful', 'dirty', 'old'], options_es: ['feo', 'bonito', 'sucio', 'viejo'], explanation: 'lelijk = ugly.', explanation_es: 'lelijk = feo.', level: 'A2' },
  { id: 'adj-voc-sterk', kind: 'vocab', prompt: 'sterk', gloss_en: null, gloss_es: null, answer: 'strong', answer_es: 'fuerte', options: ['strong', 'weak', 'heavy', 'healthy'], options_es: ['fuerte', 'débil', 'pesado', 'sano'], explanation: 'sterk = strong.', explanation_es: 'sterk = fuerte.', level: 'A2' },
  { id: 'adj-voc-zwak', kind: 'vocab', prompt: 'zwak', gloss_en: null, gloss_es: null, answer: 'weak', answer_es: 'débil', options: ['weak', 'strong', 'thin', 'sick'], options_es: ['débil', 'fuerte', 'delgado', 'enfermo'], explanation: 'zwak = weak.', explanation_es: 'zwak = débil.', level: 'B1' },
  { id: 'adj-voc-druk', kind: 'vocab', prompt: 'druk', gloss_en: null, gloss_es: null, answer: 'busy', answer_es: 'ajetreado', options: ['busy', 'calm', 'full', 'tired'], options_es: ['ajetreado', 'tranquilo', 'lleno', 'cansado'], explanation: 'druk = busy / hectic.', explanation_es: 'druk = ajetreado.', level: 'B1' },
  { id: 'adj-voc-rustig', kind: 'vocab', prompt: 'rustig', gloss_en: null, gloss_es: null, answer: 'calm', answer_es: 'tranquilo', options: ['calm', 'busy', 'boring', 'cold'], options_es: ['tranquilo', 'ajetreado', 'aburrido', 'frío'], explanation: 'rustig = calm / quiet.', explanation_es: 'rustig = tranquilo.', level: 'B1' },
  { id: 'adj-voc-lekker', kind: 'vocab', prompt: 'lekker', gloss_en: null, gloss_es: null, answer: 'tasty', answer_es: 'sabroso', options: ['tasty', 'ugly', 'dirty', 'boring'], options_es: ['sabroso', 'feo', 'sucio', 'aburrido'], explanation: 'lekker = tasty / nice (also “pleasant”).', explanation_es: 'lekker = sabroso / rico (también “agradable”).', level: 'A2' },
  { id: 'adj-voc-gezond', kind: 'vocab', prompt: 'gezond', gloss_en: null, gloss_es: null, answer: 'healthy', answer_es: 'sano', options: ['healthy', 'sick', 'strong', 'clean'], options_es: ['sano', 'enfermo', 'fuerte', 'limpio'], explanation: 'gezond = healthy.', explanation_es: 'gezond = sano.', level: 'A2' },
  { id: 'adj-voc-moe', kind: 'vocab', prompt: 'moe', gloss_en: null, gloss_es: null, answer: 'tired', answer_es: 'cansado', options: ['tired', 'busy', 'sad', 'sick'], options_es: ['cansado', 'ajetreado', 'triste', 'enfermo'], explanation: 'moe = tired.', explanation_es: 'moe = cansado.', level: 'A2' },
  { id: 'adj-voc-blij', kind: 'vocab', prompt: 'blij', gloss_en: null, gloss_es: null, answer: 'happy', answer_es: 'contento', options: ['happy', 'sad', 'angry', 'tired'], options_es: ['contento', 'triste', 'enfadado', 'cansado'], explanation: 'blij = happy / glad.', explanation_es: 'blij = contento.', level: 'A1' },
  { id: 'adj-voc-verdrietig', kind: 'vocab', prompt: 'verdrietig', gloss_en: null, gloss_es: null, answer: 'sad', answer_es: 'triste', options: ['sad', 'happy', 'tired', 'sick'], options_es: ['triste', 'contento', 'cansado', 'enfermo'], explanation: 'verdrietig = sad.', explanation_es: 'verdrietig = triste.', level: 'A2' },

  // ── DEGREE: comparative / superlative (options = forms) ────────────────────
  { id: 'adj-deg-klein-c', kind: 'degree', prompt: 'klein', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'kleiner', answer_es: null, options: ['kleiner', 'kleinst', 'kleinere', 'klener'], options_es: null, explanation: 'Comparative = stem + -er: klein → kleiner.', explanation_es: 'Comparativo = raíz + -er: klein → kleiner.', level: 'A2' },
  { id: 'adj-deg-snel-c', kind: 'degree', prompt: 'snel', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'sneller', answer_es: null, options: ['sneller', 'sneler', 'snelder', 'snelst'], options_es: null, explanation: 'Short vowel + consonant doubles: snel → sneller.', explanation_es: 'Vocal corta + consonante se duplica: snel → sneller.', level: 'A2' },
  { id: 'adj-deg-mooi-c', kind: 'degree', prompt: 'mooi', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'mooier', answer_es: null, options: ['mooier', 'mooor', 'mooiste', 'mojer'], options_es: null, explanation: 'mooi → mooier.', explanation_es: 'mooi → mooier.', level: 'A2' },
  { id: 'adj-deg-duur-c', kind: 'degree', prompt: 'duur', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'duurder', answer_es: null, options: ['duurder', 'duurer', 'duurst', 'durer'], options_es: null, explanation: 'Adjectives ending in -r add -der: duur → duurder.', explanation_es: 'Los adjetivos terminados en -r añaden -der: duur → duurder.', level: 'B1' },
  { id: 'adj-deg-oud-c', kind: 'degree', prompt: 'oud', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'ouder', answer_es: null, options: ['ouder', 'ouwer', 'oudst', 'oudere'], options_es: null, explanation: 'oud → ouder.', explanation_es: 'oud → ouder.', level: 'A2' },
  { id: 'adj-deg-warm-c', kind: 'degree', prompt: 'warm', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'warmer', answer_es: null, options: ['warmer', 'warmder', 'warmst', 'warmere'], options_es: null, explanation: 'warm → warmer.', explanation_es: 'warm → warmer.', level: 'A2' },
  { id: 'adj-deg-lekker-c', kind: 'degree', prompt: 'lekker', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'lekkerder', answer_es: null, options: ['lekkerder', 'lekkerer', 'lekkerst', 'lekkere'], options_es: null, explanation: 'Ends in -r → add -der: lekker → lekkerder.', explanation_es: 'Termina en -r → añade -der: lekker → lekkerder.', level: 'B1' },
  { id: 'adj-deg-goed-c', kind: 'degree', prompt: 'goed', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'beter', answer_es: null, options: ['beter', 'goeder', 'goeier', 'best'], options_es: null, explanation: 'Irregular: goed → beter → best.', explanation_es: 'Irregular: goed → beter → best.', level: 'A2' },
  { id: 'adj-deg-veel-c', kind: 'degree', prompt: 'veel', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'meer', answer_es: null, options: ['meer', 'veler', 'veelder', 'meest'], options_es: null, explanation: 'Irregular: veel → meer → meest.', explanation_es: 'Irregular: veel → meer → meest.', level: 'B1' },
  { id: 'adj-deg-weinig-c', kind: 'degree', prompt: 'weinig', gloss_en: 'comparative (–er)', gloss_es: 'comparativo (–er)', answer: 'minder', answer_es: null, options: ['minder', 'weiniger', 'minst', 'weinigder'], options_es: null, explanation: 'Irregular: weinig → minder → minst.', explanation_es: 'Irregular: weinig → minder → minst.', level: 'B1' },
  { id: 'adj-deg-groot-s', kind: 'degree', prompt: 'groot', gloss_en: 'superlative (–st)', gloss_es: 'superlativo (–st)', answer: 'grootst', answer_es: null, options: ['grootst', 'grotest', 'grootster', 'groost'], options_es: null, explanation: 'Superlative = stem + -st: groot → grootst.', explanation_es: 'Superlativo = raíz + -st: groot → grootst.', level: 'A2' },
  { id: 'adj-deg-klein-s', kind: 'degree', prompt: 'klein', gloss_en: 'superlative (–st)', gloss_es: 'superlativo (–st)', answer: 'kleinst', answer_es: null, options: ['kleinst', 'klenst', 'kleiner', 'kleinster'], options_es: null, explanation: 'klein → kleinst.', explanation_es: 'klein → kleinst.', level: 'A2' },
  { id: 'adj-deg-goed-s', kind: 'degree', prompt: 'goed', gloss_en: 'superlative (–st)', gloss_es: 'superlativo (–st)', answer: 'best', answer_es: null, options: ['best', 'goedst', 'beter', 'bestst'], options_es: null, explanation: 'Irregular: goed → beter → best.', explanation_es: 'Irregular: goed → beter → best.', level: 'A2' },
  { id: 'adj-deg-mooi-s', kind: 'degree', prompt: 'mooi', gloss_en: 'superlative (–st)', gloss_es: 'superlativo (–st)', answer: 'mooist', answer_es: null, options: ['mooist', 'mooiest', 'mooier', 'moost'], options_es: null, explanation: 'mooi → mooist.', explanation_es: 'mooi → mooist.', level: 'A2' },
  { id: 'adj-deg-graag-s', kind: 'degree', prompt: 'graag', gloss_en: 'superlative (–st)', gloss_es: 'superlativo (–st)', answer: 'liefst', answer_es: null, options: ['liefst', 'graagst', 'liever', 'graagt'], options_es: null, explanation: 'Irregular: graag → liever → liefst.', explanation_es: 'Irregular: graag → liever → liefst.', level: 'B1' },
  { id: 'adj-deg-veel-s', kind: 'degree', prompt: 'veel', gloss_en: 'superlative (–st)', gloss_es: 'superlativo (–st)', answer: 'meest', answer_es: null, options: ['meest', 'veelst', 'meer', 'meeste'], options_es: null, explanation: 'Irregular: veel → meer → meest.', explanation_es: 'Irregular: veel → meer → meest.', level: 'B1' },

  // ── OPPOSITE: pick the antonym (gloss = meaning of the prompt) ─────────────
  { id: 'adj-opp-groot', kind: 'opposite', prompt: 'groot', gloss_en: 'big', gloss_es: 'grande', answer: 'klein', answer_es: null, options: ['klein', 'groot', 'hoog', 'dik'], options_es: null, explanation: 'groot ↔ klein (big ↔ small).', explanation_es: 'groot ↔ klein (grande ↔ pequeño).', level: 'A1' },
  { id: 'adj-opp-snel', kind: 'opposite', prompt: 'snel', gloss_en: 'fast', gloss_es: 'rápido', answer: 'langzaam', answer_es: null, options: ['langzaam', 'snel', 'laat', 'zwaar'], options_es: null, explanation: 'snel ↔ langzaam (fast ↔ slow).', explanation_es: 'snel ↔ langzaam (rápido ↔ lento).', level: 'A2' },
  { id: 'adj-opp-goed', kind: 'opposite', prompt: 'goed', gloss_en: 'good', gloss_es: 'bueno', answer: 'slecht', answer_es: null, options: ['slecht', 'goed', 'mooi', 'sterk'], options_es: null, explanation: 'goed ↔ slecht (good ↔ bad).', explanation_es: 'goed ↔ slecht (bueno ↔ malo).', level: 'A1' },
  { id: 'adj-opp-mooi', kind: 'opposite', prompt: 'mooi', gloss_en: 'beautiful', gloss_es: 'bonito', answer: 'lelijk', answer_es: null, options: ['lelijk', 'mooi', 'vies', 'oud'], options_es: null, explanation: 'mooi ↔ lelijk (beautiful ↔ ugly).', explanation_es: 'mooi ↔ lelijk (bonito ↔ feo).', level: 'A2' },
  { id: 'adj-opp-duur', kind: 'opposite', prompt: 'duur', gloss_en: 'expensive', gloss_es: 'caro', answer: 'goedkoop', answer_es: null, options: ['goedkoop', 'duur', 'arm', 'rijk'], options_es: null, explanation: 'duur ↔ goedkoop (expensive ↔ cheap).', explanation_es: 'duur ↔ goedkoop (caro ↔ barato).', level: 'A2' },
  { id: 'adj-opp-jong', kind: 'opposite', prompt: 'jong', gloss_en: 'young', gloss_es: 'joven', answer: 'oud', answer_es: null, options: ['oud', 'jong', 'klein', 'nieuw'], options_es: null, explanation: 'jong ↔ oud (young ↔ old).', explanation_es: 'jong ↔ oud (joven ↔ viejo).', level: 'A1' },
  { id: 'adj-opp-warm', kind: 'opposite', prompt: 'warm', gloss_en: 'warm', gloss_es: 'caliente', answer: 'koud', answer_es: null, options: ['koud', 'warm', 'heet', 'nat'], options_es: null, explanation: 'warm ↔ koud (warm ↔ cold).', explanation_es: 'warm ↔ koud (caliente ↔ frío).', level: 'A1' },
  { id: 'adj-opp-lang', kind: 'opposite', prompt: 'lang', gloss_en: 'long', gloss_es: 'largo', answer: 'kort', answer_es: null, options: ['kort', 'lang', 'hoog', 'breed'], options_es: null, explanation: 'lang ↔ kort (long ↔ short).', explanation_es: 'lang ↔ kort (largo ↔ corto).', level: 'A2' },
  { id: 'adj-opp-hoog', kind: 'opposite', prompt: 'hoog', gloss_en: 'high', gloss_es: 'alto', answer: 'laag', answer_es: null, options: ['laag', 'hoog', 'diep', 'kort'], options_es: null, explanation: 'hoog ↔ laag (high ↔ low).', explanation_es: 'hoog ↔ laag (alto ↔ bajo).', level: 'A2' },
  { id: 'adj-opp-sterk', kind: 'opposite', prompt: 'sterk', gloss_en: 'strong', gloss_es: 'fuerte', answer: 'zwak', answer_es: null, options: ['zwak', 'sterk', 'dun', 'ziek'], options_es: null, explanation: 'sterk ↔ zwak (strong ↔ weak).', explanation_es: 'sterk ↔ zwak (fuerte ↔ débil).', level: 'A2' },
  { id: 'adj-opp-rijk', kind: 'opposite', prompt: 'rijk', gloss_en: 'rich', gloss_es: 'rico', answer: 'arm', answer_es: null, options: ['arm', 'rijk', 'duur', 'leeg'], options_es: null, explanation: 'rijk ↔ arm (rich ↔ poor).', explanation_es: 'rijk ↔ arm (rico ↔ pobre).', level: 'A2' },
  { id: 'adj-opp-moeilijk', kind: 'opposite', prompt: 'moeilijk', gloss_en: 'difficult', gloss_es: 'difícil', answer: 'makkelijk', answer_es: null, options: ['makkelijk', 'moeilijk', 'snel', 'zwaar'], options_es: null, explanation: 'moeilijk ↔ makkelijk (difficult ↔ easy).', explanation_es: 'moeilijk ↔ makkelijk (difícil ↔ fácil).', level: 'A2' },
  { id: 'adj-opp-vol', kind: 'opposite', prompt: 'vol', gloss_en: 'full', gloss_es: 'lleno', answer: 'leeg', answer_es: null, options: ['leeg', 'vol', 'dik', 'breed'], options_es: null, explanation: 'vol ↔ leeg (full ↔ empty).', explanation_es: 'vol ↔ leeg (lleno ↔ vacío).', level: 'A2' },
  { id: 'adj-opp-schoon', kind: 'opposite', prompt: 'schoon', gloss_en: 'clean', gloss_es: 'limpio', answer: 'vuil', answer_es: null, options: ['vuil', 'schoon', 'nat', 'oud'], options_es: null, explanation: 'schoon ↔ vuil (clean ↔ dirty).', explanation_es: 'schoon ↔ vuil (limpio ↔ sucio).', level: 'A2' },
  { id: 'adj-opp-zwaar', kind: 'opposite', prompt: 'zwaar', gloss_en: 'heavy', gloss_es: 'pesado', answer: 'licht', answer_es: null, options: ['licht', 'zwaar', 'dik', 'sterk'], options_es: null, explanation: 'zwaar ↔ licht (heavy ↔ light).', explanation_es: 'zwaar ↔ licht (pesado ↔ ligero).', level: 'A2' },
  { id: 'adj-opp-blij', kind: 'opposite', prompt: 'blij', gloss_en: 'happy', gloss_es: 'contento', answer: 'verdrietig', answer_es: null, options: ['verdrietig', 'blij', 'boos', 'moe'], options_es: null, explanation: 'blij ↔ verdrietig (happy ↔ sad).', explanation_es: 'blij ↔ verdrietig (contento ↔ triste).', level: 'A2' },
  { id: 'adj-opp-dik', kind: 'opposite', prompt: 'dik', gloss_en: 'thick / fat', gloss_es: 'grueso / gordo', answer: 'dun', answer_es: null, options: ['dun', 'dik', 'breed', 'smal'], options_es: null, explanation: 'dik ↔ dun (thick ↔ thin).', explanation_es: 'dik ↔ dun (grueso ↔ delgado).', level: 'A2' },
  { id: 'adj-opp-breed', kind: 'opposite', prompt: 'breed', gloss_en: 'wide', gloss_es: 'ancho', answer: 'smal', answer_es: null, options: ['smal', 'breed', 'kort', 'laag'], options_es: null, explanation: 'breed ↔ smal (wide ↔ narrow).', explanation_es: 'breed ↔ smal (ancho ↔ estrecho).', level: 'B1' },
];

async function main() {
  console.log(`Inserting ${rows.length} adjective exercises…`);
  const { error } = await supabase.from('adjective_exercises').upsert(rows, { onConflict: 'id' });
  if (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
  console.log('Done.');
}

main();
